# Generated by Django 5.0.6 on 2024-05-23 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='static/images/')),
                ('date', models.DateField(auto_now_add=True)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.itemtype')),
            ],
        ),
    ]
